version:  '3.2'

services:

  column:
    image: "cassandra"
    networks:
      - nosql
    environment:
      JVM_OPTS: -Xms512m -Xmx512m
    ports:
      - 9042:9042

  document:
    image: "mongo:latest"
    networks:
      - nosql
    ports:
      - 27017:27017

networks:
  nosql:
